version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ${OUTPUT_DIR}:/results
    
  db:
    image: postgis/postgis:16-3.4-alpine
    env_file:
      - .env
    ports:
      - 5430:5432
    restart: on-failure
    volumes:
      - postgis_data:/var/lib/postgresql/data  

volumes:
  postgis_data:

