version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery
      - rabbitmq
    env_file:
      - .env
    volumes:
      - ${OUTPUT_DIR}:/results
    
  db:
    image: postgis/postgis:16-3.4-alpine
    env_file:
      - .env
    ports:
      - 5430:5432
    restart: on-failure
    volumes:
      - postgis_data:/var/lib/postgresql/data  

  celery:
    build: 
      context: .
      dockerfile: ./celery/Dockerfile
    env_file:
      - .env
    command: celery -A roseapi worker --loglevel=info
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq


volumes:
  postgis_data:

